export const languageData = [
    {
        locale: 'en',
        translation: {
            ourservices: 'Our services are just a click',
            awayfromhome: 'away from your home',
            becleanisaplatform: 'Be Clean is a platform that offers you all personal and home care and car cleaning services by approved service providers at the best prices and offers.',
            personalizeyourexp: 'Personalize your experience',
            language: 'Language',
            country: 'Country',
            getstarted: 'GET STARTED',
            italy: 'Italy',
            pleaseLoginHere: 'Please Login Here',
            emailAddress: 'Email Address',
            email: 'E-mail',
            password: 'Password',
            forgotPassword: 'Forgot Password?',
            rememberme: 'Remember me',
            donthaveaccount: 'Don’t have account?',
            signup: 'SIGN UP',
            or: 'OR',
            signIn: 'SIGN IN',
            pleaseRegisterHere: 'Please Register Here!',
            fullname: 'Full Name',
            confirmpassword: 'Confirm password',
            role: 'Role',
            alreadyhaveanaccount: 'Already have an account ',
            iagreeto: 'I agree to',
            TermsConditions: 'Terms & Conditions',
            and1: '&',
            privacyPolicy: 'Privacy Policy',
            otp: 'OTP',
            enter6digitcode: 'Enter 6 digit code sent to your email address to verify your identity',
            sendagain: 'Send again',
            verify: 'VERIFY',
            success: 'Success',
            registerissucessfullyhaveenjoy: 'Register is sucessfully have enjoy!',
            resetyourpassword: 'Reset your password',
            enteryouremail: 'Enter your email address to reset your Password',
            rememberyourpassword: 'Remember your password?',
            sendOtp: 'SEND OTP',
            changePassword: 'Change password',
            enteryournewpassword: 'Enter your new password to access to your account',
            save: 'SAVE',
            home: 'Home',
            booking: 'Booking',
            map: 'Map',
            notification: 'Notification',
            profile: 'Profile',
            Favorites: 'Favorites',
            paymentMethod: 'Payment Method',
            referralDiscounts: 'Referral Discounts',
            preferences: 'Preferences',
            fAQ: 'FAQ',
            settings: 'Settings',
            editProfile: 'Edit Profile',
            phoneNo: 'Phone No',
            address: 'Address',
            gender: 'Gender',
            male: 'Male',
            female: 'Female',
            SAVE: 'SAVE',
            notificationReceivedw: 'Notification received',
            new: 'New',
            allFavorites: 'All Favorites',
            discountinFavorites: 'Discount in Favorites',
            creditCards: 'Credit Cards',
            addanewcard: 'Add a new card',
            cardNumber: 'Card Number',
            cvvNumber: 'CVV Number',
            expiryDate: 'Expiry Date',
            creditDebitCard: 'Credit/Debit Card',
            getfreecredit: 'Get Free Credit',
            sharethebestkepthome: "Share the best-kept home care secret! Share the link to give your friend ILT 40 off their booking! Once they use it to book, you will automatically receive ILT 40 credit added to your account! Now that's what we call a win-win-win!",
            sharefreecredit: 'Share free credit',
            office: 'Office',
            company: 'Company',
            hospital: 'Hospital',
            flexibletime: 'Flexible time ',
            recurring: 'Recurring',
            service: 'Service',
            request: 'Request',
            cleaning: 'Cleaning',
            preferences: 'Preferences',
            search: 'Search',
            howdoibookacleaning: 'How do I book a cleaning service?',
            howdoipayforthe: 'How do I pay for the cleaning services?',
            howdoicontact: 'How do I contact customer support?',
            feedback: 'Feedback',
            supportandhelp: 'Support & Help Center',
            deletemyaccount: 'Delete my account',
            tellusaboutyour: 'Tell us about your experience',
            yourfeedback: 'Your feedback',
            send: 'SEND',
            support: 'Support',
            deleteacount: 'Delete Account',

            areyousureyouwant: 'Are you sure you want to delete your account?',
            warning: 'Warning:',
            deleting: 'Deleting your account will permanently remove all of your:',
            bookingHistory: 'Booking history',
            savedpayment: 'Saved payment methods',
            personalPrefrences: 'Personal preferences',
            todeleteyouraccount: 'To Delete your Account Confirm your Password',
            password: 'Password',
            bytappingconfirm: 'By tapping confirm, you agree to the',
            of: 'of',
            clein: 'CLE IN',
            enterpassword: 'Enter password',
            delete: 'DELETE',
            specialservices: 'Special Services',
            featureforyou: 'Featured For You',
            cleaningathome: 'Cleaning at Home',
            cleaningatcompany: 'Cleaning at Company',
            cleaningathospital: 'Cleaning at Hospital',
            cleaningatoffice: 'Cleaning at Offices',
            cleaningatfactory: 'Cleaning at Factory',
            serviceprovider: 'Service Provider',
            book: 'BOOK',
            title: 'Title',
            description: 'Description',
            price: 'Price',
            location: 'Location',
            reviews: 'Reviews',
            seeAll: 'See All',
            all: 'All',
            bookservice: 'Book Service',
            next: 'NEXT',
            howmanyhoursdoyou: 'How many hours do you need your professional to stay?',
            howmanyprofessional: 'How many professionals do you need?',
            anyspecificinstruction: 'Any Specific Instructions ?',
            yourtext: 'Your Text',
            whenwouldyoulike: 'When would you like to schedule your service?',
            selectDate: 'Select Date',
            selectTime: 'Select Time',
            to: 'To',
            addNote: 'Add Note',
            pay: 'Pay',
            amount: 'Amount',
            vat: 'VAT',
            total: 'Total',
            pending: 'Pending',
            upcoming: 'Upcoming',
            ongoing: 'Ongoing',
            completed: 'Completed',
            chat: 'Chat',
            typeamsg: 'Type a message ',
            cancel: 'CANCEL',
            addreview: 'Add Review',
            status: 'Status',
            comment: 'Comment',
            successful: 'Successful',
            cancelbooking: 'Cancel Booking',
            bookingCancel: 'Booking Cancel',
            others: 'Others',
            enteryourreason: 'Enter your reason',
            pleaseselectthereason: 'Please select the reason for cancellation:',
            schedulechange: 'Schedule change',
            weatherconditions: 'Weather conditions',
            Ihavealternativeoption: 'I have alternative options',
            dob: 'Date of Birth',
            myads: 'My ads',
            analytics: 'Analytics',
            edit: 'EDIT',
            accept: 'ACCEPT',
            cancel: 'CANCEL',
            customerInfo: 'Customer Info',
            createService: 'Create Service',
            selectCategory: 'Select Category',
            adfixedrate: 'Ad Fixed Rate',
            photos: 'Photos',
            openingTime: 'Opening Time',
            closingTime: 'Closing Time',
            availability: 'Availability',
            reviewconfirm: 'Review & Confirm',
            post: 'POST',
            logout: 'Logout',
            myStats: 'My Stats',
            totalServices: 'Total Services ',
            rating: 'Rating',
            totalbookings: 'Total bookings ',
            totalCancellations: 'Total cancellations',
            themeModeD: 'Theme (Dark Mode)',
            themeModeNormal: 'Theme (Normal)',
        }
    },
    {
        locale: 'it',
        translation: {
            ourservices: 'I nostri servizi sono solo a un clic',
            awayfromhome: 'di distanza da casa tua',
            becleanisaplatform: 'Be Clean è una piattaforma che ti offre tutti i servizi di cura personale, pulizia domestica e pulizia auto forniti da professionisti approvati ai migliori prezzi e offerte.',
            personalizeyourexp: 'Personalizza la tua esperienza',
            language: 'Lingua',
            country: 'Paese',
            getstarted: 'INIZIA',
            italy: 'Italia',
            pleaseLoginHere: 'Accedi qui',
            emailAddress: 'Indirizzo email',
            email: 'E-mail',
            password: 'Password',
            forgotPassword: 'Hai dimenticato la password?',
            rememberme: 'Ricordami',
            donthaveaccount: 'Non hai un account?',
            signup: 'REGISTRATI',
            or: 'OPPURE',
            signIn: 'ACCEDI',
            pleaseRegisterHere: 'Registrati qui!',
            fullname: 'Nome completo',
            confirmpassword: 'Conferma password',
            role: 'Ruolo',
            alreadyhaveanaccount: 'Hai già un account?',
            iagreeto: 'Accetto i',
            TermsConditions: 'Termini e condizioni',
            and1: 'e',
            privacyPolicy: 'Informativa sulla privacy',
            otp: 'OTP',
            enter6digitcode: 'Inserisci il codice a 6 cifre inviato alla tua email per verificare la tua identità',
            sendagain: 'Invia di nuovo',
            verify: 'VERIFICA',
            success: 'Successo',
            registerissucessfullyhaveenjoy: 'Registrazione avvenuta con successo! Buon divertimento!',
            resetyourpassword: 'Reimposta la tua password',
            enteryouremail: 'Inserisci il tuo indirizzo email per reimpostare la password',
            rememberyourpassword: 'Ricordi la tua password?',
            sendOtp: 'INVIA OTP',
            changePassword: 'Cambia password',
            enteryournewpassword: 'Inserisci la tua nuova password per accedere al tuo account',
            save: 'SALVA',
            home: 'Home',
            booking: 'Prenotazioni',
            map: 'Mappa',
            notification: 'Notifiche',
            profile: 'Profilo',
            Favorites: 'Preferiti',
            paymentMethod: 'Metodo di pagamento',
            referralDiscounts: 'Sconti di riferimento',
            preferences: 'Preferenze',
            fAQ: 'FAQ',
            settings: 'Impostazioni',
            editProfile: 'Modifica profilo',
            phoneNo: 'Numero di telefono',
            address: 'Indirizzo',
            gender: 'Genere',
            male: 'Maschio',
            female: 'Femmina',
            SAVE: 'SALVA',
            notificationReceivedw: 'Notifica ricevuta',
            new: 'Nuovo',
            allFavorites: 'Tutti i Preferiti',
            discountinFavorites: 'Sconto nei Preferiti',
            creditCards: 'Carte di credito',
            addanewcard: 'Aggiungi una nuova carta',
            cardNumber: 'Numero della carta',
            cvvNumber: 'Numero CVV',
            expiryDate: 'Data di scadenza',
            creditDebitCard: 'Carta di credito/debito',
            getfreecredit: 'Ottieni credito gratuito',
            sharethebestkepthome: "Condividi il segreto meglio custodito per la cura della casa! Condividi il link per dare al tuo amico 40 ILT di sconto sulla sua prenotazione! Una volta che lo usa, riceverai automaticamente 40 ILT di credito aggiunto al tuo account! Questo è ciò che chiamiamo un vantaggio per tutti!",
            sharefreecredit: 'Condividi credito gratuito',
            office: 'Ufficio',
            company: 'Azienda',
            hospital: 'Ospedale',
            flexibletime: 'Orario flessibile',
            recurring: 'Ricorrente',
            service: 'Servizio',
            request: 'Richiesta',
            cleaning: 'Pulizia',
            preferences: 'Preferenze',
            search: 'Cerca',
            howdoibookacleaning: 'Come prenoto un servizio di pulizia?',
            howdoipayforthe: 'Come pago per i servizi di pulizia?',
            howdoicontact: 'Come contatto il servizio clienti?',
            feedback: 'Feedback',
            supportandhelp: 'Supporto e Centro assistenza',
            deletemyaccount: 'Elimina il mio account',
            tellusaboutyour: 'Raccontaci la tua esperienza',
            yourfeedback: 'Il tuo feedback',
            send: 'INVIA',
            support: 'Supporto',
            deleteacount: 'Elimina account',
            areyousureyouwant: 'Sei sicuro di voler eliminare il tuo account?',
            warning: 'Attenzione:',
            deleting: 'Eliminare il tuo account rimuoverà permanentemente tutto il tuo:',
            bookingHistory: 'Cronologia delle prenotazioni',
            savedpayment: 'Metodi di pagamento salvati',
            personalPrefrences: 'Preferenze personali',
            todeleteyouraccount: 'Per eliminare il tuo account conferma la tua password',
            password: 'Password',
            bytappingconfirm: 'Toccando conferma, accetti i',
            of: 'di',
            clein: 'CLE IN',
            enterpassword: 'Inserisci la password',
            delete: 'ELIMINA',
            specialservices: 'Servizi speciali',
            featureforyou: 'In evidenza per te',
            cleaningathome: 'Pulizia a casa',
            cleaningatcompany: 'Pulizia in azienda',
            cleaningathospital: 'Pulizia in ospedale',
            cleaningatoffice: 'Pulizia negli uffici',
            cleaningatfactory: 'Pulizia in fabbrica',
            serviceprovider: 'Fornitore di servizi',
            book: 'PRENOTA',
            title: 'Titolo',
            description: 'Descrizione',
            price: 'Prezzo',
            location: 'Località',
            reviews: 'Recensioni',
            seeAll: 'Vedi tutto',
            all: 'Tutto',
            bookservice: 'Prenota Servizio',
            next: 'AVANTI',
            howmanyhoursdoyou: 'Quante ore hai bisogno del professionista?',
            howmanyprofessional: 'Quanti professionisti hai bisogno?',
            anyspecificinstruction: 'Istruzioni specifiche?',
            yourtext: 'Il tuo testo',
            whenwouldyoulike: 'Quando desideri programmare il servizio?',
            selectDate: 'Seleziona Data',
            selectTime: 'Seleziona Ora',
            to: 'A',
            addNote: 'Aggiungi nota',
            pay: 'PAGA',
            amount: 'Importo',
            vat: 'IVA',
            total: 'Totale',
            pending: 'In sospeso',
            upcoming: 'Prossimo',
            ongoing: 'In corso',
            completed: 'Completato',
            chat: 'Chat',
            typeamsg: 'Scrivi un messaggio',
            cancel: 'ANNULLA',
            addreview: 'Aggiungi Recensione',
            status: 'Stato',
            comment: 'Commento',
            successful: 'Riuscito',
            cancelbooking: 'Annulla prenotazione',
            bookingCancel: 'Prenotazione annullata',
            others: 'Altro',
            enteryourreason: 'Inserisci il motivo',
            pleaseselectthereason: 'Seleziona il motivo della cancellazione:',
            schedulechange: 'Cambio di programma',
            weatherconditions: 'Condizioni meteo',
            Ihavealternativeoption: 'Ho altre opzioni',
            dob: 'Data di nascita',
            myads: 'I miei annunci',
            analytics: 'Analitica',
            edit: 'MODIFICA',
            accept: 'ACCETTA',
            cancel: 'ANNULLA',
            customerInfo: 'Informazioni cliente',
            createService: 'Crea servizio',
            selectCategory: 'Seleziona categoria',
            adfixedrate: 'Aggiungi tariffa fissa',
            photos: 'Foto',
            openingTime: 'Orario di apertura',
            closingTime: 'Orario di chiusura',
            availability: 'Disponibilità',
            reviewconfirm: 'Revisione e conferma',
            post: 'PUBBLICA',
            logout: 'Esci',
            myStats: 'Le mie statistiche',
            totalServices: 'Servizi totali',
            rating: 'Valutazione',
            totalbookings: 'Prenotazioni totali',
            totalCancellations: 'Cancellazioni totali',
            themeModeD: 'Tema (Modalità Scura)',
            themeModeNormal: 'Tema (Normale)',
        }

    },
    {
        locale: 'sp',
        translation: {
            ourservices: 'Nuestros servicios están a un clic',
            awayfromhome: 'de distancia de tu hogar',
            becleanisaplatform: 'Be Clean es una plataforma que te ofrece todos los servicios de cuidado personal, limpieza del hogar y limpieza de autos por proveedores de servicios aprobados a los mejores precios y ofertas.',
            personalizeyourexp: 'Personaliza tu experiencia',
            language: 'Idioma',
            country: 'País',
            getstarted: 'COMENZAR',
            italy: 'Italia',
            pleaseLoginHere: 'Inicia sesión aquí',
            emailAddress: 'Dirección de correo electrónico',
            email: 'Correo electrónico',
            password: 'Contraseña',
            forgotPassword: '¿Olvidaste tu contraseña?',
            rememberme: 'Recuérdame',
            donthaveaccount: '¿No tienes una cuenta?',
            signup: 'REGÍSTRATE',
            or: 'O',
            signIn: 'INICIAR SESIÓN',
            pleaseRegisterHere: '¡Regístrate aquí!',
            fullname: 'Nombre completo',
            confirmpassword: 'Confirmar contraseña',
            role: 'Rol',
            alreadyhaveanaccount: '¿Ya tienes una cuenta?',
            iagreeto: 'Acepto los',
            TermsConditions: 'Términos y condiciones',
            and1: 'y',
            privacyPolicy: 'Política de privacidad',
            otp: 'OTP',
            enter6digitcode: 'Ingresa el código de 6 dígitos enviado a tu correo electrónico para verificar tu identidad',
            sendagain: 'Enviar de nuevo',
            verify: 'VERIFICAR',
            success: 'Éxito',
            registerissucessfullyhaveenjoy: '¡Registro exitoso, disfruta!',
            resetyourpassword: 'Restablece tu contraseña',
            enteryouremail: 'Ingresa tu dirección de correo electrónico para restablecer tu contraseña',
            rememberyourpassword: '¿Recuerdas tu contraseña?',
            sendOtp: 'ENVIAR OTP',
            changePassword: 'Cambiar contraseña',
            enteryournewpassword: 'Ingresa tu nueva contraseña para acceder a tu cuenta',
            save: 'GUARDAR',
            home: 'Inicio',
            booking: 'Reservas',
            map: 'Mapa',
            notification: 'Notificaciones',
            profile: 'Perfil',
            Favorites: 'Favoritos',
            paymentMethod: 'Método de pago',
            referralDiscounts: 'Descuentos por referencia',
            preferences: 'Preferencias',
            fAQ: 'Preguntas frecuentes',
            settings: 'Configuraciones',
            editProfile: 'Editar perfil',
            phoneNo: 'Número de teléfono',
            address: 'Dirección',
            gender: 'Género',
            male: 'Hombre',
            female: 'Mujer',
            SAVE: 'GUARDAR',
            notificationReceivedw: 'Notificación recibida',
            new: 'Nuevo',
            allFavorites: 'Todos los favoritos',
            discountinFavorites: 'Descuento en favoritos',
            creditCards: 'Tarjetas de crédito',
            addanewcard: 'Agregar una nueva tarjeta',
            cardNumber: 'Número de tarjeta',
            cvvNumber: 'Número CVV',
            expiryDate: 'Fecha de expiración',
            creditDebitCard: 'Tarjeta de crédito/débito',
            getfreecredit: 'Obtén crédito gratis',
            sharethebestkepthome: "¡Comparte el secreto mejor guardado del cuidado del hogar! Comparte el enlace para darle a tu amigo 40 ILT de descuento en su reserva. ¡Una vez que lo use, recibirás automáticamente 40 ILT de crédito en tu cuenta! ¡Eso es lo que llamamos un ganar-ganar-ganar!",
            sharefreecredit: 'Compartir crédito gratis',
            office: 'Oficina',
            company: 'Compañía',
            hospital: 'Hospital',
            flexibletime: 'Horario flexible',
            recurring: 'Recurrente',
            service: 'Servicio',
            request: 'Solicitud',
            cleaning: 'Limpieza',
            preferences: 'Preferencias',
            search: 'Buscar',
            howdoibookacleaning: '¿Cómo reservo un servicio de limpieza?',
            howdoipayforthe: '¿Cómo pago por los servicios de limpieza?',
            howdoicontact: '¿Cómo contacto al servicio de atención al cliente?',
            feedback: 'Comentarios',
            supportandhelp: 'Centro de ayuda y soporte',
            deletemyaccount: 'Eliminar mi cuenta',
            tellusaboutyour: 'Cuéntanos sobre tu experiencia',
            yourfeedback: 'Tu comentario',
            send: 'ENVIAR',
            support: 'Soporte',
            deleteacount: 'Eliminar cuenta',
            areyousureyouwant: '¿Estás seguro de que deseas eliminar tu cuenta?',
            warning: 'Advertencia:',
            deleting: 'Eliminar tu cuenta eliminará permanentemente:',
            bookingHistory: 'Historial de reservas',
            savedpayment: 'Métodos de pago guardados',
            personalPrefrences: 'Preferencias personales',
            todeleteyouraccount: 'Para eliminar tu cuenta, confirma tu contraseña',
            password: 'Contraseña',
            bytappingconfirm: 'Al tocar confirmar, aceptas los',
            of: 'de',
            clein: 'CLE IN',
            enterpassword: 'Ingresa la contraseña',
            delete: 'ELIMINAR',
            specialservices: 'Servicios especiales',
            featureforyou: 'Destacado para ti',
            cleaningathome: 'Limpieza en casa',
            cleaningatcompany: 'Limpieza en la empresa',
            cleaningathospital: 'Limpieza en hospital',
            cleaningatoffice: 'Limpieza en oficina',
            cleaningatfactory: 'Limpieza en fábrica',
            serviceprovider: 'Proveedor de servicios',
            book: 'RESERVAR',
            title: 'Título',
            description: 'Descripción',
            price: 'Precio',
            location: 'Ubicación',
            reviews: 'Reseñas',
            seeAll: 'Ver todo',
            all: 'Todo',
            bookservice: 'Reservar Servicio',
            next: 'SIGUIENTE',
            howmanyhoursdoyou: '¿Cuántas horas necesitas que el profesional se quede?',
            howmanyprofessional: '¿Cuántos profesionales necesitas?',
            anyspecificinstruction: '¿Alguna instrucción específica?',
            yourtext: 'Tu texto',
            whenwouldyoulike: '¿Cuándo te gustaría programar el servicio?',
            selectDate: 'Seleccionar fecha',
            selectTime: 'Seleccionar hora',
            to: 'A',
            addNote: 'Agregar nota',
            pay: 'PAGAR',
            amount: 'Monto',
            vat: 'IVA',
            total: 'Total',
            pending: 'Pendiente',
            upcoming: 'Próximo',
            ongoing: 'En curso',
            completed: 'Completado',
            chat: 'Chat',
            typeamsg: 'Escribe un mensaje',
            cancel: 'CANCELAR',
            addreview: 'Agregar reseña',
            status: 'Estado',
            comment: 'Comentario',
            successful: 'Exitoso',
            cancelbooking: 'Cancelar reserva',
            bookingCancel: 'Reserva cancelada',
            others: 'Otros',
            enteryourreason: 'Ingresa tu motivo',
            pleaseselectthereason: 'Selecciona el motivo de la cancelación:',
            schedulechange: 'Cambio de horario',
            weatherconditions: 'Condiciones climáticas',
            Ihavealternativeoption: 'Tengo opciones alternativas',
            dob: 'Fecha de nacimiento',
            myads: 'Mis anuncios',
            analytics: 'Analítica',
            edit: 'EDITAR',
            accept: 'ACEPTAR',
            cancel: 'CANCELAR',
            customerInfo: 'Información del cliente',
            createService: 'Crear Servicio',
            selectCategory: 'Seleccionar Categoría',
            adfixedrate: 'Agregar Tarifa Fija',
            photos: 'Fotos',
            openingTime: 'Hora de apertura',
            closingTime: 'Hora de cierre',
            availability: 'Disponibilidad',
            reviewconfirm: 'Revisar y Confirmar',
            post: 'PUBLICAR',
            logout: 'Cerrar sesión',
            myStats: 'Mis estadísticas',
            totalServices: 'Servicios Totales',
            rating: 'Calificación',
            totalbookings: 'Reservas Totales',
            totalCancellations: 'Cancelaciones Totales',
            themeModeD: 'Tema (Modo Oscuro)',
            themeModeNormal: 'Tema (Normal)',
        }

    },
    {
        locale: 'gr',
        translation: {
            ourservices: 'Unsere Dienstleistungen sind nur einen Klick',
            awayfromhome: 'von deinem Zuhause entfernt',
            becleanisaplatform: 'Be Clean ist eine Plattform, die Ihnen alle persönlichen, häuslichen und Autoreinigungsdienste von zugelassenen Dienstleistern zu den besten Preisen und Angeboten bietet.',
            personalizeyourexp: 'Personalisieren Sie Ihr Erlebnis',
            language: 'Sprache',
            country: 'Land',
            getstarted: 'STARTEN',
            italy: 'Italien',
            pleaseLoginHere: 'Bitte hier einloggen',
            emailAddress: 'E-Mail-Adresse',
            email: 'E-Mail',
            password: 'Passwort',
            forgotPassword: 'Passwort vergessen?',
            rememberme: 'Erinnere dich an mich',
            donthaveaccount: 'Haben Sie kein Konto?',
            signup: 'REGISTRIEREN',
            or: 'ODER',
            signIn: 'ANMELDEN',
            pleaseRegisterHere: 'Bitte hier registrieren!',
            fullname: 'Vollständiger Name',
            confirmpassword: 'Passwort bestätigen',
            role: 'Rolle',
            alreadyhaveanaccount: 'Haben Sie bereits ein Konto?',
            iagreeto: 'Ich stimme den',
            TermsConditions: 'Geschäftsbedingungen',
            and1: 'und',
            privacyPolicy: 'Datenschutzrichtlinie',
            otp: 'OTP',
            enter6digitcode: 'Geben Sie den 6-stelligen Code ein, der an Ihre E-Mail-Adresse gesendet wurde, um Ihre Identität zu verifizieren',
            sendagain: 'Erneut senden',
            verify: 'VERIFIZIEREN',
            success: 'Erfolg',
            registerissucessfullyhaveenjoy: 'Registrierung erfolgreich, viel Spaß!',
            resetyourpassword: 'Passwort zurücksetzen',
            enteryouremail: 'Geben Sie Ihre E-Mail-Adresse ein, um Ihr Passwort zurückzusetzen',
            rememberyourpassword: 'Erinnern Sie sich an Ihr Passwort?',
            sendOtp: 'OTP SENDEN',
            changePassword: 'Passwort ändern',
            enteryournewpassword: 'Geben Sie Ihr neues Passwort ein, um auf Ihr Konto zuzugreifen',
            save: 'SPEICHERN',
            home: 'Startseite',
            booking: 'Buchung',
            map: 'Karte',
            notification: 'Benachrichtigung',
            profile: 'Profil',
            Favorites: 'Favoriten',
            paymentMethod: 'Zahlungsmethode',
            referralDiscounts: 'Empfehlungsrabatte',
            preferences: 'Einstellungen',
            fAQ: 'Häufige Fragen',
            settings: 'Einstellungen',
            editProfile: 'Profil bearbeiten',
            phoneNo: 'Telefonnummer',
            address: 'Adresse',
            gender: 'Geschlecht',
            male: 'Männlich',
            female: 'Weiblich',
            SAVE: 'SPEICHERN',
            notificationReceivedw: 'Benachrichtigung erhalten',
            new: 'Neu',
            allFavorites: 'Alle Favoriten',
            discountinFavorites: 'Rabatt bei Favoriten',
            creditCards: 'Kreditkarten',
            addanewcard: 'Neue Karte hinzufügen',
            cardNumber: 'Kartennummer',
            cvvNumber: 'CVV-Nummer',
            expiryDate: 'Ablaufdatum',
            creditDebitCard: 'Kredit-/Debitkarte',
            getfreecredit: 'Kostenloses Guthaben erhalten',
            sharethebestkepthome: "Teilen Sie das bestgehütete Geheimnis der Haushaltsführung! Teilen Sie den Link, um Ihrem Freund 40 ILT Rabatt auf seine Buchung zu geben! Sobald er es verwendet, erhalten Sie automatisch 40 ILT Guthaben auf Ihr Konto gutgeschrieben! Das nennen wir eine Win-Win-Win-Situation!",
            sharefreecredit: 'Kostenloses Guthaben teilen',
            office: 'Büro',
            company: 'Unternehmen',
            hospital: 'Krankenhaus',
            flexibletime: 'Flexible Zeit',
            recurring: 'Wiederkehrend',
            service: 'Dienstleistung',
            request: 'Anfrage',
            cleaning: 'Reinigung',
            preferences: 'Einstellungen',
            search: 'Suchen',
            howdoibookacleaning: 'Wie buche ich einen Reinigungsservice?',
            howdoipayforthe: 'Wie bezahle ich für die Reinigungsdienste?',
            howdoicontact: 'Wie kontaktiere ich den Kundensupport?',
            feedback: 'Feedback',
            supportandhelp: 'Support- und Hilfe-Center',
            deletemyaccount: 'Mein Konto löschen',
            tellusaboutyour: 'Erzählen Sie uns von Ihrem Erlebnis',
            yourfeedback: 'Ihr Feedback',
            send: 'SENDEN',
            support: 'Support',
            deleteacount: 'Konto löschen',
            areyousureyouwant: 'Sind Sie sicher, dass Sie Ihr Konto löschen möchten?',
            warning: 'Warnung:',
            deleting: 'Das Löschen Ihres Kontos entfernt dauerhaft alle Ihre:',
            bookingHistory: 'Buchungsverlauf',
            savedpayment: 'Gespeicherte Zahlungsmethoden',
            personalPrefrences: 'Persönliche Vorlieben',
            todeleteyouraccount: 'Um Ihr Konto zu löschen, bestätigen Sie Ihr Passwort',
            password: 'Passwort',
            bytappingconfirm: 'Durch Tippen auf Bestätigen stimmen Sie den',
            of: 'von',
            clein: 'CLE IN',
            enterpassword: 'Passwort eingeben',
            delete: 'LÖSCHEN',
            specialservices: 'Spezialdienste',
            featureforyou: 'Empfohlen für Sie',
            cleaningathome: 'Reinigung zu Hause',
            cleaningatcompany: 'Reinigung im Unternehmen',
            cleaningathospital: 'Reinigung im Krankenhaus',
            cleaningatoffice: 'Reinigung im Büro',
            cleaningatfactory: 'Reinigung in der Fabrik',
            serviceprovider: 'Dienstleister',
            book: 'BUCHEN',
            title: 'Titel',
            description: 'Beschreibung',
            price: 'Preis',
            location: 'Standort',
            reviews: 'Bewertungen',
            seeAll: 'Alle ansehen',
            all: 'Alle',
            bookservice: 'Dienst buchen',
            next: 'WEITER',
            howmanyhoursdoyou: 'Wie viele Stunden benötigen Sie den Fachmann?',
            howmanyprofessional: 'Wie viele Fachleute benötigen Sie?',
            anyspecificinstruction: 'Gibt es besondere Anweisungen?',
            yourtext: 'Ihr Text',
            whenwouldyoulike: 'Wann möchten Sie Ihren Service planen?',
            selectDate: 'Datum auswählen',
            selectTime: 'Uhrzeit auswählen',
            to: 'Bis',
            addNote: 'Notiz hinzufügen',
            pay: 'BEZAHLEN',
            amount: 'Betrag',
            vat: 'MwSt.',
            total: 'Gesamt',
            pending: 'Ausstehend',
            upcoming: 'Bevorstehend',
            ongoing: 'Laufend',
            completed: 'Abgeschlossen',
            chat: 'Chat',
            typeamsg: 'Nachricht schreiben',
            cancel: 'ABBRECHEN',
            addreview: 'Bewertung hinzufügen',
            status: 'Status',
            comment: 'Kommentar',
            successful: 'Erfolgreich',
            cancelbooking: 'Buchung stornieren',
            bookingCancel: 'Buchung storniert',
            others: 'Sonstige',
            enteryourreason: 'Geben Sie Ihren Grund ein',
            pleaseselectthereason: 'Bitte wählen Sie den Stornierungsgrund:',
            schedulechange: 'Zeitplanänderung',
            weatherconditions: 'Wetterbedingungen',
            Ihavealternativeoption: 'Ich habe eine alternative Option',
            dob: 'Geburtsdatum',
            myads: 'Meine Anzeigen',
            analytics: 'Analytik',
            edit: 'BEARBEITEN',
            accept: 'AKZEPTIEREN',
            cancel: 'ABBRECHEN',
            customerInfo: 'Kundeninformation',
            createService: 'Dienst erstellen',
            selectCategory: 'Kategorie auswählen',
            adfixedrate: 'Festpreis hinzufügen',
            photos: 'Fotos',
            openingTime: 'Öffnungszeit',
            closingTime: 'Schließzeit',
            availability: 'Verfügbarkeit',
            reviewconfirm: 'Überprüfen und bestätigen',
            post: 'POSTEN',
            logout: 'Abmelden',
            myStats: 'Meine Statistiken',
            totalServices: 'Gesamtanzahl der Dienste',
            rating: 'Bewertung',
            totalbookings: 'Gesamtanzahl der Buchungen',
            totalCancellations: 'Gesamtanzahl der Stornierungen',
            themeModeD: 'Thema (Dunkelmodus)',
            themeModeNormal: 'Thema (Normal)',
        }

    },
    {
        locale: 'fr',
        translation: {
            ourservices: 'Nos services sont juste un clic',
            awayfromhome: 'de chez vous',
            becleanisaplatform: 'Be Clean est une plateforme qui vous offre tous les services de soins personnels, de nettoyage domestique et de nettoyage de voiture par des prestataires de services approuvés aux meilleurs prix et offres.',
            personalizeyourexp: 'Personnalisez votre expérience',
            language: 'Langue',
            country: 'Pays',
            getstarted: 'COMMENCER',
            italy: 'Italie',
            pleaseLoginHere: 'Veuillez vous connecter ici',
            emailAddress: 'Adresse e-mail',
            email: 'E-mail',
            password: 'Mot de passe',
            forgotPassword: 'Mot de passe oublié ?',
            rememberme: 'Souviens-toi de moi',
            donthaveaccount: 'Vous n\'avez pas de compte ?',
            signup: 'S\'INSCRIRE',
            or: 'OU',
            signIn: 'SE CONNECTER',
            pleaseRegisterHere: 'Veuillez vous inscrire ici !',
            fullname: 'Nom complet',
            confirmpassword: 'Confirmer le mot de passe',
            role: 'Rôle',
            alreadyhaveanaccount: 'Vous avez déjà un compte ?',
            iagreeto: 'J\'accepte les',
            TermsConditions: 'Conditions générales',
            and1: 'et',
            privacyPolicy: 'Politique de confidentialité',
            otp: 'OTP',
            enter6digitcode: 'Entrez le code à 6 chiffres envoyé à votre adresse e-mail pour vérifier votre identité',
            sendagain: 'Renvoyer',
            verify: 'VÉRIFIER',
            success: 'Succès',
            registerissucessfullyhaveenjoy: 'Inscription réussie, profitez-en !',
            resetyourpassword: 'Réinitialisez votre mot de passe',
            enteryouremail: 'Entrez votre adresse e-mail pour réinitialiser votre mot de passe',
            rememberyourpassword: 'Vous vous souvenez de votre mot de passe ?',
            sendOtp: 'ENVOYER OTP',
            changePassword: 'Changer le mot de passe',
            enteryournewpassword: 'Entrez votre nouveau mot de passe pour accéder à votre compte',
            save: 'ENREGISTRER',
            home: 'Accueil',
            booking: 'Réservation',
            map: 'Carte',
            notification: 'Notification',
            profile: 'Profil',
            Favorites: 'Favoris',
            paymentMethod: 'Méthode de paiement',
            referralDiscounts: 'Réductions de parrainage',
            preferences: 'Préférences',
            fAQ: 'FAQ',
            settings: 'Paramètres',
            editProfile: 'Modifier le profil',
            phoneNo: 'Numéro de téléphone',
            address: 'Adresse',
            gender: 'Genre',
            male: 'Homme',
            female: 'Femme',
            SAVE: 'ENREGISTRER',
            notificationReceivedw: 'Notification reçue',
            new: 'Nouveau',
            allFavorites: 'Tous les favoris',
            discountinFavorites: 'Réduction dans les favoris',
            creditCards: 'Cartes de crédit',
            addanewcard: 'Ajouter une nouvelle carte',
            cardNumber: 'Numéro de carte',
            cvvNumber: 'Numéro CVV',
            expiryDate: 'Date d\'expiration',
            creditDebitCard: 'Carte de crédit/débit',
            getfreecredit: 'Obtenez un crédit gratuit',
            sharethebestkepthome: "Partagez le meilleur secret des soins à domicile ! Partagez le lien pour offrir à votre ami 40 ILT de réduction sur sa réservation ! Une fois utilisé, vous recevrez automatiquement un crédit de 40 ILT ajouté à votre compte ! Voilà ce que nous appelons une situation gagnant-gagnant !",
            sharefreecredit: 'Partager le crédit gratuit',
            office: 'Bureau',
            company: 'Entreprise',
            hospital: 'Hôpital',
            flexibletime: 'Temps flexible',
            recurring: 'Récurrent',
            service: 'Service',
            request: 'Demande',
            cleaning: 'Nettoyage',
            preferences: 'Préférences',
            search: 'Rechercher',
            howdoibookacleaning: 'Comment réserver un service de nettoyage ?',
            howdoipayforthe: 'Comment payer les services de nettoyage ?',
            howdoicontact: 'Comment contacter le service client ?',
            feedback: 'Retour d\'information',
            supportandhelp: 'Centre de support et d\'aide',
            deletemyaccount: 'Supprimer mon compte',
            tellusaboutyour: 'Parlez-nous de votre expérience',
            yourfeedback: 'Vos retours',
            send: 'ENVOYER',
            support: 'Assistance',
            deleteacount: 'Supprimer le compte',
            areyousureyouwant: 'Êtes-vous sûr de vouloir supprimer votre compte ?',
            warning: 'Avertissement :',
            deleting: 'La suppression de votre compte supprimera définitivement tous vos :',
            bookingHistory: 'Historique des réservations',
            savedpayment: 'Méthodes de paiement enregistrées',
            personalPrefrences: 'Préférences personnelles',
            todeleteyouraccount: 'Pour supprimer votre compte, confirmez votre mot de passe',
            password: 'Mot de passe',
            bytappingconfirm: 'En appuyant sur confirmer, vous acceptez les',
            of: 'de',
            clein: 'CLE IN',
            enterpassword: 'Entrez le mot de passe',
            delete: 'SUPPRIMER',
            specialservices: 'Services spéciaux',
            featureforyou: 'En vedette pour vous',
            cleaningathome: 'Nettoyage à domicile',
            cleaningatcompany: 'Nettoyage en entreprise',
            cleaningathospital: 'Nettoyage à l\'hôpital',
            cleaningatoffice: 'Nettoyage au bureau',
            cleaningatfactory: 'Nettoyage à l\'usine',
            serviceprovider: 'Prestataire de services',
            book: 'RÉSERVER',
            title: 'Titre',
            description: 'Description',
            price: 'Prix',
            location: 'Lieu',
            reviews: 'Avis',
            seeAll: 'Voir tout',
            all: 'Tout',
            bookservice: 'Réserver un service',
            next: 'SUIVANT',
            howmanyhoursdoyou: 'Combien d\'heures avez-vous besoin de votre professionnel ?',
            howmanyprofessional: 'Combien de professionnels avez-vous besoin ?',
            anyspecificinstruction: 'Des instructions spécifiques ?',
            yourtext: 'Votre texte',
            whenwouldyoulike: 'Quand souhaitez-vous planifier votre service ?',
            selectDate: 'Sélectionner la date',
            selectTime: 'Sélectionner l\'heure',
            to: 'À',
            addNote: 'Ajouter une note',
            pay: 'PAYER',
            amount: 'Montant',
            vat: 'TVA',
            total: 'Total',
            pending: 'En attente',
            upcoming: 'À venir',
            ongoing: 'En cours',
            completed: 'Terminé',
            chat: 'Chat',
            typeamsg: 'Tapez un message',
            cancel: 'ANNULER',
            addreview: 'Ajouter un avis',
            status: 'Statut',
            comment: 'Commentaire',
            successful: 'Réussi',
            cancelbooking: 'Annuler la réservation',
            bookingCancel: 'Réservation annulée',
            others: 'Autres',
            enteryourreason: 'Entrez votre raison',
            pleaseselectthereason: 'Veuillez sélectionner la raison de l\'annulation :',
            schedulechange: 'Changement d\'horaire',
            weatherconditions: 'Conditions météorologiques',
            Ihavealternativeoption: 'J\'ai une autre option',
            dob: 'Date de naissance',
            myads: 'Mes annonces',
            analytics: 'Analytique',
            edit: 'MODIFIER',
            accept: 'ACCEPTER',
            cancel: 'ANNULER',
            customerInfo: 'Informations client',
            createService: 'Créer un service',
            selectCategory: 'Sélectionner une catégorie',
            adfixedrate: 'Ajouter un tarif fixe',
            photos: 'Photos',
            openingTime: 'Heure d\'ouverture',
            closingTime: 'Heure de fermeture',
            availability: 'Disponibilité',
            reviewconfirm: 'Vérifier et confirmer',
            post: 'POSTER',
            logout: 'Déconnexion',
            myStats: 'Mes statistiques',
            totalServices: 'Nombre total de services',
            rating: 'Évaluation',
            totalbookings: 'Total des réservations',
            totalCancellations: 'Total des annulations',
            themeModeD: 'Thème (Mode Sombre)',
            themeModeNormal: 'Thème (Normal)',
        }

    },

];

export const appLanguages = [
    {
        id: '0',
        name: 'English',
        code: 'en'
    },
    {
        id: '1',
        name: 'Italian',
        code: 'it'
    },
    {
        id: '2',
        name: 'Spanish',
        code: 'sp'
    },
    {
        id: '3',
        name: 'German',
        code: 'gr'
    },
    {
        id: '4',
        name: 'French',
        code: 'fr'
    },
];
