export const languageData = [
    {
        locale: 'en',
        translation: {
            ourservices: 'Our services are just a click',
            awayfromhome: 'away from your home',
            becleanisaplatform: 'Be Clean is a platform that offers you all personal and home care and car cleaning services by approved service providers at the best prices and offers.',
            personalizeyourexp: 'Personalize your experience',
            language: 'Language',
            country: 'Country',
            getstarted: 'GET STARTED',
            italy: 'Italy',
            pleaseLoginHere: 'Login as Customer or Cleaner',
            emailAddress: 'Email Address',
            email: 'E-mail',
            password: 'Password',
            forgotPassword: 'Forgot Password?',
            rememberme: 'Remember me',
            donthaveaccount: 'Don’t have account?',
            signup: 'SIGN UP',
            or: 'OR',
            signIn: 'SIGN IN',
            // pleaseRegisterHere: 'Please Register Here!',
            pleaseRegisterHere: 'Register as Customer Only!',
            fullname: 'Full Name',
            confirmpassword: 'Confirm password',
            role: 'Role',
            alreadyhaveanaccount: 'Already have an account?',
            iagreeto: 'I agree to',
            TermsConditions: 'Terms & Conditions',
            and1: '&',
            privacyPolicy: 'Privacy Policy',
            otp: 'OTP',
            enter6digitcode: 'Enter 6 digit code sent to your email address to verify your identity',
            sendagain: 'Send again',
            verify: 'VERIFY',
            success: 'Success',
            registerissucessfullyhaveenjoy: 'Register is sucessfully have enjoy!',
            resetyourpassword: 'Reset your password',
            enteryouremail: 'Enter your email address to reset your Password',
            rememberyourpassword: 'Remember your password?',
            sendOtp: 'SEND OTP',
            changePassword: 'Change password',
            enteryournewpassword: 'Enter your new password to access to your account',
            save: 'SAVE',
            home: 'Home',
            booking: 'Booking',
            map: 'Map',
            notification: 'Notification',
            profile: 'Profile',
            Favorites: 'Favorites',
            paymentMethod: 'Payment Method',
            referralDiscounts: 'Referral Discounts',
            preferences: 'Preferences',
            fAQ: 'FAQ',
            settings: 'Settings',
            editProfile: 'Edit Profile',
            phoneNo: 'Phone No',
            address: 'Address',
            gender: 'Gender',
            male: 'Male',
            female: 'Female',
            SAVE: 'SAVE',
            notificationReceivedw: 'Notification received',
            new: 'New',
            allFavorites: 'All Favorites',
            discountinFavorites: 'Discount in Favorites',
            creditCards: 'Credit Cards',
            addanewcard: 'Add a new card',
            cardNumber: 'Card Number',
            cvvNumber: 'CVV Number',
            expiryDate: 'Expiry Date',
            creditDebitCard: 'Credit/Debit Card',
            getfreecredit: 'Get Free Credit',
            sharethebestkepthome: "Share the best-kept home care secret! Share the link to give your friend ILT 40 off their booking! Once they use it to book, you will automatically receive ILT 40 credit added to your account! Now that's what we call a win-win-win!",
            sharefreecredit: 'Share free credit',
            office: 'Office',
            company: 'Company',
            hospital: 'Hospital',
            flexibletime: 'Flexible time ',
            recurring: 'Recurring',
            service: 'Service',
            request: 'Request',
            cleaning: 'Cleaning',
            preferences: 'Preferences',
            search: 'Search',
            howdoibookacleaning: 'How do I book a cleaning service?',
            howdoipayforthe: 'How do I pay for the cleaning services?',
            howdoicontact: 'How do I contact customer support?',
            feedback: 'Feedback',
            supportandhelp: 'Support & Help Center',
            deletemyaccount: 'Delete my account',
            tellusaboutyour: 'Tell us about your experience',
            yourfeedback: 'Your feedback',
            send: 'SEND',
            support: 'Support',
            deleteacount: 'Delete Account',

            areyousureyouwant: 'Are you sure you want to delete your account?',
            warning: 'Warning:',
            deleting: 'Deleting your account will permanently remove all of your:',
            bookingHistory: 'Booking history',
            savedpayment: 'Saved payment methods',
            personalPrefrences: 'Personal preferences',
            todeleteyouraccount: 'To Delete your Account Confirm your Password',
            password: 'Password',
            bytappingconfirm: 'By tapping confirm, you agree to the',
            of: 'of',
            clein: 'CLE IN',
            enterpassword: 'Enter password',
            delete: 'DELETE',
            specialservices: 'Special Services',
            featureforyou: 'Featured For You',
            cleaningathome: 'Cleaning at Home',
            cleaningatcompany: 'Cleaning at Company',
            cleaningathospital: 'Cleaning at Hospital',
            cleaningatoffice: 'Cleaning at Offices',
            cleaningatfactory: 'Cleaning at Factory',
            serviceprovider: 'Service Provider',
            book: 'BOOK',
            title: 'Title',
            description: 'Description',
            price: 'Price',
            location: 'Location',
            reviews: 'Reviews',
            seeAll: 'See All',
            all: 'All',
            bookservice: 'Book Service',
            next: 'NEXT',
            // howmanyhoursdoyou: 'How many hours do you need your professional to stay?',
            howmanyhoursdoyou: 'How many hours do you need?',
            howmanyprofessional: 'How many professionals do you need?',
            anyspecificinstruction: 'Any Specific Instructions ?',
            yourtext: 'Your Text',
            whenwouldyoulike: 'When would you like to schedule your service?',
            selectDate: 'Select Date',
            selectTime: 'Select Time',
            to: 'to',
            addNote: 'Add Note',
            pay: 'Pay',
            amount: 'Amount',
            vat: 'VAT',
            total: 'Total',
            pending: 'Pending',
            upcoming: 'Upcoming',
            ongoing: 'Ongoing',
            completed: 'Completed',
            chat: 'Chat',
            typeamsg: 'Type a message ',
            cancel: 'CANCEL',
            addreview: 'Add Review',
            status: 'Status',
            comment: 'Comment',
            successful: 'Successful',
            cancelbooking: 'Cancel Booking',
            bookingCancel: 'Booking Cancel',
            others: 'Others',
            enteryourreason: 'Enter your reason',
            pleaseselectthereason: 'Please select the reason for cancellation:',
            schedulechange: 'Schedule change',
            weatherconditions: 'Weather conditions',
            Ihavealternativeoption: 'I have alternative options',
            dob: 'Date of Birth',
            myads: 'My Ads',
            analytics: 'Analytics',
            edit: 'EDIT',
            accept: 'ACCEPT',
            cancel: 'CANCEL',
            customerInfo: 'Customer Info',
            createService: 'Create Service',
            selectCategory: 'Select Category',
            adfixedrate: 'Ad Fixed Rate',
            photos: 'Photos',
            openingTime: 'Opening Time',
            closingTime: 'Closing Time',
            availability: 'Availability',
            reviewconfirm: 'Review & Confirm',
            post: 'POST',
            logout: 'Logout',
            myStats: 'My Stats',
            totalServices: 'Total Services ',
            rating: 'Rating',
            totalbookings: 'Total bookings ',
            totalCancellations: 'Total cancellations',
            themeModeD: 'Theme (Dark Mode)',
            themeModeNormal: 'Theme (Normal)',
            cleaningandhygiene: 'Cleaning and Hygiene Services',
            HomeMaintenanceServices: 'Home Maintenance Services',
            InstallationServices: 'Installation Services',
            RenovationServices: 'Renovation Service',
            // JobRequest: 'Job Request',
            JobRequest: 'Requests',
            Subscription: 'Subscription',
            ServiceProviderInfo: 'Service Provider Info',
            UpgradeToPremium: 'Upgrade to Premium',
            UnlimitedPostJobs: 'Unlimited Post Jobs, Services, and so more',
            MonthsString: 'months',
            Subscribe: 'Subscribe',
            WhenwillIbebilled: 'When will I be billed?',
            YourItunesAccount: 'Your iTunes Account will be billed at the end of your trial period (if applicable) or on confirmation of your subscription.',
            jobs: 'Jobs',
            myjobs: 'My Jobs',
            viewAll: 'View All',
            services: 'Services',
            subCategories: 'Sub Categories',
            apply: 'Apply',
            turnOnGps: 'Turn on GPS',
            locationNotAvailable: 'Location services are unavailable.',
            Sign: 'Sign',
            Clear: 'Clear',
            jobCreatorName: 'Job Creator Name:',
            jobCreatorSignature: 'Job Creator Signature:',
            taphereforsignature: 'Tap here for signature:',
            serviceproviderName: 'Service Provider Name:',
            serviceproviderSignature: 'Service Provider Signature:',
            NonDisclosure: 'Non-Disclosure Agreement (NDA)',
            NDA: 'NDA',
            createJob: 'Create Job',
            rooms: 'Create Job',
            roomsNumber: 'Number of rooms',
            areaSize: 'Room areas size',
            chooseyourfreq: 'Choose Your Frequency',

            weekly: 'Weekly',
            every2weeks: 'Every 2 weeks',
            oneTime: 'One Time',

            enjoyhavingthesame: 'The same cleaner every week.',
            enjoyhavingthesame2: 'The same cleaner every 2 weeks.',
            perfectPickwhen: 'When you schedule is uncertain',

            pauseorcancelanytime: 'Cancel at anytime',

            selectRepeatService: 'Select',
            mostPopular: 'Most Popular',
            rathernotsay: 'Rather not say',
            registerasacleaner: 'Register as a cleaner',
            noIhavethem: 'No, I have them',
            yesPlease: 'Yes, Please',
            needCleaningMaterials: 'Need cleaning materials?',
            job: 'Job',
            cleaners: 'Cleaners',
            workFrequency: 'Work frequency',
            additionalService: 'Additional Services',
            Oven: 'Oven',
            Laundry: 'Laundry',
            Fridge: 'Fridge',
            Ironing: 'Ironing',
            Balcony: 'Balcony',
            Cupboard: 'Cupboard',


            howlongshouldibookfor: 'How long should I book for?',
            whichmaterialswill: 'Which materials will Pulizie Di Casa bring?',
            recommendedDuration: 'Recommended Duration',

            cleaningDuration: 'Cleaning Duration',
            Studio: 'Studio',
            Bedroom1: '1 Room',
            Bedroom2: '2 Room',
            Bedroom3: '3 Room',
            Bedroom4: '4 Room',
            Bedroom5: '5 Room',
            Bedroom5: '6 Room',
            Hour1: '1 hour',
            Hour1to2: '1-2 hours',
            Hour2to3: '2-3 hours',
            Hour3to4: '3-4 hours',
            Hour4to5: '4-5 hours',
            Hour5to6: '5-6 hours',
            Hour6to7: '6-7 hours',
            ExpressCleaning: 'Express Cleaning',
            Hourforquickcleanup: '1 Hour for quick cleanup',
            VillasResident: 'Villas Resident',
            Extrahourrecommendedforvillas: 'Extra hour recommended for villas',
            RegularCleaningList: 'Regular Cleaning List',

            KitchenDishescountertops: 'Kitchen: Dishes & countertops',
            Minutes30: '30 Minutes',
            BathroomCleaningwiping: 'Bathroom: Cleaning & wiping',
            BedroomTidyingbedmaking: 'Bedroom: Tidying & bed making',
            Minutes20: '20 Minutes',
            GeneralDustingMoppingVacuumingtrashremoval: 'General: Dusting, Mopping, Vacuuming & trash removal',
            Minutes40: '40 Minutes',

            bookyourhomecleaning: 'Book your home cleaning with the Pulizie Di Casa Cleaning Kit',
            CleaningHome: 'Cleaning Home',
            FloorCleaner: 'Floor Cleaner',
            Multipurposecleaner: 'Multipurpose Cleaner',
            KitchenCleaner: 'Kitchen Cleaner',
            GlassCleaner: 'Glass Cleaner',
            FurniturePolish: 'Furniture Polish',
            ToiletCleaner: 'Toilet Cleaner',
            CleaningEquipment: 'Cleaning Equipment',
            VacuumCleaner: 'Vacuum Cleaner',
            Mop: 'Mop',
            BucketSpinner: 'Bucket & Spinner',
            MicrofiberCloth: 'Microfiber Cloth',
            SpongCloth: 'Spong Cloth',
            Securingpad: 'Securing pad',

        }
    },
    {
        locale: 'it',
        translation: {
            ourservices: 'I nostri servizi sono solo a un clic',
            awayfromhome: 'di distanza da casa tua',
            becleanisaplatform: 'Be Clean è una piattaforma che ti offre tutti i servizi di cura personale, pulizia domestica e pulizia auto forniti da professionisti approvati ai migliori prezzi e offerte.',
            personalizeyourexp: 'Personalizza la tua esperienza',
            language: 'Lingua',
            country: 'Paese',
            getstarted: 'INIZIA',
            italy: 'Italia',
            // pleaseLoginHere: 'Accedi qui',
            pleaseLoginHere: 'Accedi come Cliente o Addetto alle Pulizie',
            emailAddress: 'Indirizzo email',
            email: 'E-mail',
            password: 'Password',
            forgotPassword: 'Hai dimenticato la password?',
            rememberme: 'Ricordami',
            donthaveaccount: 'Non hai un account?',
            signup: 'REGISTRATI',
            or: 'OPPURE',
            signIn: 'ACCEDI',
            // pleaseRegisterHere: 'Registrati qui!',
            pleaseRegisterHere: 'Registrati solo come Cliente!',
            fullname: 'Nome completo',
            confirmpassword: 'Conferma password',
            role: 'Ruolo',
            alreadyhaveanaccount: 'Hai già un account?',
            iagreeto: 'Accetto i',
            TermsConditions: 'Termini e condizioni',
            and1: 'e',
            privacyPolicy: 'Informativa sulla privacy',
            otp: 'OTP',
            enter6digitcode: 'Inserisci il codice a 6 cifre inviato alla tua email per verificare la tua identità',
            sendagain: 'Invia di nuovo',
            verify: 'VERIFICA',
            success: 'Successo',
            registerissucessfullyhaveenjoy: 'Registrazione avvenuta con successo! Buon divertimento!',
            resetyourpassword: 'Reimposta la tua password',
            enteryouremail: 'Inserisci il tuo indirizzo email per reimpostare la password',
            rememberyourpassword: 'Ricordi la tua password?',
            sendOtp: 'INVIA OTP',
            changePassword: 'Cambia password',
            enteryournewpassword: 'Inserisci la tua nuova password per accedere al tuo account',
            save: 'SALVA',
            home: 'Home',
            booking: 'Prenotazioni',
            map: 'Mappa',
            notification: 'Notifiche',
            profile: 'Profilo',
            Favorites: 'Preferiti',
            paymentMethod: 'Metodo di pagamento',
            referralDiscounts: 'Sconti di riferimento',
            preferences: 'Preferenze',
            fAQ: 'FAQ',
            settings: 'Impostazioni',
            editProfile: 'Modifica profilo',
            phoneNo: 'Numero di telefono',
            address: 'Indirizzo',
            gender: 'Genere',
            male: 'Maschio',
            female: 'Femmina',
            SAVE: 'SALVA',
            notificationReceivedw: 'Notifica ricevuta',
            new: 'Nuovo',
            allFavorites: 'Tutti i Preferiti',
            discountinFavorites: 'Sconto nei Preferiti',
            creditCards: 'Carte di credito',
            addanewcard: 'Aggiungi una nuova carta',
            cardNumber: 'Numero della carta',
            cvvNumber: 'Numero CVV',
            expiryDate: 'Data di scadenza',
            creditDebitCard: 'Carta di credito/debito',
            getfreecredit: 'Ottieni credito gratuito',
            sharethebestkepthome: "Condividi il segreto meglio custodito per la cura della casa! Condividi il link per dare al tuo amico 40 ILT di sconto sulla sua prenotazione! Una volta che lo usa, riceverai automaticamente 40 ILT di credito aggiunto al tuo account! Questo è ciò che chiamiamo un vantaggio per tutti!",
            sharefreecredit: 'Condividi credito gratuito',
            office: 'Ufficio',
            company: 'Azienda',
            hospital: 'Ospedale',
            flexibletime: 'Orario flessibile',
            recurring: 'Ricorrente',
            service: 'Servizio',
            request: 'Richiesta',
            cleaning: 'Pulizia',
            preferences: 'Preferenze',
            search: 'Cerca',
            howdoibookacleaning: 'Come prenoto un servizio di pulizia?',
            howdoipayforthe: 'Come pago per i servizi di pulizia?',
            howdoicontact: 'Come contatto il servizio clienti?',
            feedback: 'Feedback',
            supportandhelp: 'Supporto e Centro assistenza',
            deletemyaccount: 'Elimina il mio account',
            tellusaboutyour: 'Raccontaci la tua esperienza',
            yourfeedback: 'Il tuo feedback',
            send: 'INVIA',
            support: 'Supporto',
            deleteacount: 'Elimina account',
            areyousureyouwant: 'Sei sicuro di voler eliminare il tuo account?',
            warning: 'Attenzione:',
            deleting: 'Eliminare il tuo account rimuoverà permanentemente tutto il tuo:',
            bookingHistory: 'Cronologia delle prenotazioni',
            savedpayment: 'Metodi di pagamento salvati',
            personalPrefrences: 'Preferenze personali',
            todeleteyouraccount: 'Per eliminare il tuo account conferma la tua password',
            password: 'Password',
            bytappingconfirm: 'Toccando conferma, accetti i',
            of: 'di',
            clein: 'CLE IN',
            enterpassword: 'Inserisci la password',
            delete: 'ELIMINA',
            specialservices: 'Servizi speciali',
            featureforyou: 'In evidenza per te',
            cleaningathome: 'Pulizia a casa',
            cleaningatcompany: 'Pulizia in azienda',
            cleaningathospital: 'Pulizia in ospedale',
            cleaningatoffice: 'Pulizia negli uffici',
            cleaningatfactory: 'Pulizia in fabbrica',
            serviceprovider: 'Fornitore di servizi',
            book: 'PRENOTA',
            title: 'Titolo',
            description: 'Descrizione',
            price: 'Prezzo',
            location: 'Località',
            reviews: 'Recensioni',
            seeAll: 'Vedi tutto',
            all: 'Tutto',
            bookservice: 'Prenota Servizio',
            next: 'AVANTI',
            // howmanyhoursdoyou: 'Quante ore hai bisogno del professionista?',
            howmanyhoursdoyou: 'Di quante ore hai bisogno?',
            howmanyprofessional: 'Quanti professionisti hai bisogno?',
            anyspecificinstruction: 'Istruzioni specifiche?',
            yourtext: 'Il tuo testo',
            whenwouldyoulike: 'Quando desideri programmare il servizio?',
            selectDate: 'Seleziona Data',
            selectTime: 'Seleziona Ora',
            to: 'A',
            addNote: 'Aggiungi nota',
            pay: 'PAGA',
            amount: 'Importo',
            vat: 'IVA',
            total: 'Totale',
            pending: 'In sospeso',
            upcoming: 'Prossimo',
            ongoing: 'In corso',
            completed: 'Completato',
            chat: 'Chat',
            typeamsg: 'Scrivi un messaggio',
            cancel: 'ANNULLA',
            addreview: 'Aggiungi Recensione',
            status: 'Stato',
            comment: 'Commento',
            successful: 'Riuscito',
            cancelbooking: 'Annulla prenotazione',
            bookingCancel: 'Prenotazione annullata',
            others: 'Altro',
            enteryourreason: 'Inserisci il motivo',
            pleaseselectthereason: 'Seleziona il motivo della cancellazione:',
            schedulechange: 'Cambio di programma',
            weatherconditions: 'Condizioni meteo',
            Ihavealternativeoption: 'Ho altre opzioni',
            dob: 'Data di nascita',
            myads: 'I miei annunci',
            analytics: 'Analitica',
            edit: 'MODIFICA',
            accept: 'ACCETTA',
            cancel: 'ANNULLA',
            customerInfo: 'Informazioni cliente',
            createService: 'Crea servizio',
            selectCategory: 'Seleziona categoria',
            adfixedrate: 'Aggiungi tariffa fissa',
            photos: 'Foto',
            openingTime: 'Orario di apertura',
            closingTime: 'Orario di chiusura',
            availability: 'Disponibilità',
            reviewconfirm: 'Revisione e conferma',
            post: 'PUBBLICA',
            logout: 'Esci',
            myStats: 'Le mie statistiche',
            totalServices: 'Servizi totali',
            rating: 'Valutazione',
            totalbookings: 'Prenotazioni totali',
            totalCancellations: 'Cancellazioni totali',
            themeModeD: 'Tema (Modalità Scura)',
            themeModeNormal: 'Tema (Normale)',
            cleaningandhygiene: 'Servizi di Pulizia e Igiene',
            HomeMaintenanceServices: 'Servizi di Manutenzione Domestica',
            InstallationServices: 'Servizi di Installazione',
            RenovationServices: 'Servizi di Ristrutturazione',
            // JobRequest: 'Richiesta di lavoro',
            JobRequest: 'Richieste',
            Subscription: 'Abbonamento',
            ServiceProviderInfo: 'Informazioni sul fornitore di servizi',
            UpgradeToPremium: 'Passa a Premium',
            UnlimitedPostJobs: 'Pubblica lavori, servizi e altro senza limiti',
            MonthsString: 'mesi',
            Subscribe: 'Iscriviti',
            WhenwillIbebilled: 'Quando sarò addebitato?',
            YourItunesAccount: 'Il tuo account iTunes sarà addebitato al termine del periodo di prova (se applicabile) o al momento della conferma dell\'abbonamento.', // Italian
            jobs: 'Lavori',
            myjobs: 'I miei lavori',
            services: 'Servizi',
            subCategories: 'Sottocategorie',
            apply: 'Applica',
            turnOnGps: 'Attiva il GPS',
            locationNotAvailable: 'Servizi di localizzazione non disponibili.',
            Sign: 'Firma',
            Clear: 'Cancella',
            jobCreatorName: 'Nome del creatore del lavoro:',
            jobCreatorSignature: 'Firma del creatore del lavoro:',
            taphereforsignature: 'Tocca qui per firmare:',
            serviceproviderName: 'Nome del fornitore di servizi:',
            serviceproviderSignature: 'Firma del fornitore di servizi:',
            NonDisclosure: 'Accordo di non divulgazione (NDA)',
            NDA: 'NDA',
            createJob: 'Crea lavoro',
            roomsNumber: 'Numero di stanze',
            areaSize: 'Dimensione delle aree delle stanze',
            chooseyourfreq: 'Scegli la tua frequenza',

            weekly: 'Settimanale',
            every2weeks: 'Ogni 2 settimane',
            oneTime: 'Una volta',

            enjoyhavingthesame: 'Lo stesso addetto alle pulizie ogni settimana.',
            enjoyhavingthesame2: 'Lo stesso addetto alle pulizie ogni 2 settimane.',
            perfectPickwhen: 'Quando il tuo programma è incerto',

            pauseorcancelanytime: 'Annulla in qualsiasi momento',

            // weekly: 'Settimanalmente',
            // enjoyhavingthesame: 'pulire ogni settimana.',
            // pauseorcancelanytime: 'Annulla come vuoi.',
            // every2weeks: 'Ogni due settimane.',
            // enjoyhavingthesame2: 'Pulizia ogni 2 settimane.',
            // oneTime: 'Una volta',
            // perfectPickwhen: 'Quando il tuo programma è incerto',

            selectRepeatService: 'Seleziona',
            mostPopular: 'Più popolare',
            rathernotsay: 'Preferisco non dirlo',
            registerasacleaner: 'Registrati come addetto alle pulizie',
            noIhavethem: 'No, li ho',
            yesPlease: 'Sì, per favore',
            needCleaningMaterials: 'Hai bisogno di materiali per la pulizia?',
            job: 'Lavoro',
            cleaners: 'Addetti alle pulizie',
            workFrequency: 'Frequenza del lavoro',
            additionalService: 'Servizi Aggiuntivi',
            Oven: 'Forno',
            Laundry: 'Lavanderia',
            Fridge: 'Frigorifero',
            Ironing: 'Stiratura',
            Balcony: 'Balcone',
            Cupboard: 'Credenza',

            howlongshouldibookfor: 'Per quanto tempo dovrei prenotare?',
            whichmaterialswill: 'Quali materiali porterà Pulizie Di Casa?',
            recommendedDuration: 'Durata Consigliata',

            cleaningDuration: 'Durata Pulizia',
            Studio: 'Monolocale',
            Bedroom1: '1 Stanza',
            Bedroom2: '2 Stanze',
            Bedroom3: '3 Stanze',
            Bedroom4: '4 Stanze',
            Bedroom5: '5 Stanze',
            Bedroom6: '6 Stanze',
            Hour1: '1 ora',
            Hour1to2: '1-2 ore',
            Hour2to3: '2-3 ore',
            Hour3to4: '3-4 ore',
            Hour4to5: '4-5 ore',
            Hour5to6: '5-6 ore',
            Hour6to7: '6-7 ore',
            ExpressCleaning: 'Pulizia Veloce',
            Hourforquickcleanup: '1 Ora per pulizia rapida',
            VillasResident: 'Residente in Ville',
            Extrahourrecommendedforvillas: 'Ora extra consigliata per ville',
            RegularCleaningList: 'Elenco Pulizia Regolare',

            KitchenDishescountertops: 'Cucina: Piatti e ripiani',
            Minutes30: '30 Minuti',
            BathroomCleaningwiping: 'Bagno: Pulizia e asciugatura',
            BedroomTidyingbedmaking: 'Camera da letto: Riordino e rifacimento letto',
            Minutes20: '20 Minuti',
            GeneralDustingMoppingVacuumingtrashremoval: 'Generale: Spolveratura, Lavaggio, Aspirazione e rimozione rifiuti',
            Minutes40: '40 Minuti',

            bookyourhomecleaning: 'Prenota la pulizia della tua casa con il Kit Pulizie Di Casa',
            CleaningHome: 'Pulizia Casa',
            FloorCleaner: 'Detergente per Pavimenti',
            Multipurposecleaner: 'Detergente Multiuso',
            KitchenCleaner: 'Detergente per Cucina',
            GlassCleaner: 'Detergente per Vetro',
            FurniturePolish: 'Lucidante per Mobili',
            ToiletCleaner: 'Detergente per WC',
            CleaningEquipment: 'Attrezzature per la Pulizia',
            VacuumCleaner: 'Aspirapolvere',
            Mop: 'Mocio',
            BucketSpinner: 'Secchio e Centrifuga',
            MicrofiberCloth: 'Panno in Microfibra',
            SpongCloth: 'Panno Spugna',
            Securingpad: 'Tappetino di sicurezza',


        }
    },
];

export const appLanguages = [
    {
        id: '0',
        name: 'English',
        code: 'en'
    },
    {
        id: '1',
        name: 'Italian',
        code: 'it'
    },
    // {
    //     id: '2',
    //     name: 'Spanish',
    //     code: 'sp'
    // },
    // {
    //     id: '3',
    //     name: 'German',
    //     code: 'gr'
    // },
    // {
    //     id: '4',
    //     name: 'French',
    //     code: 'fr'
    // },
];
