export const languageData = [
    {
        locale: 'en',
        translation: {
            ourservices: 'Our services are just a click',
            awayfromhome: 'away from your home',
            becleanisaplatform: 'Be Clean is a platform that offers you all personal and home care and car cleaning services by approved service providers at the best prices and offers.',
            personalizeyourexp: 'Personalize your experience',
            language: 'Language',
            country: 'Country',
            getstarted: 'GET STARTED',
            italy: 'Italy',
            pleaseLoginHere: 'Please Login Here',
            emailAddress: 'Email Address',
            email: 'E-mail',
            password: 'Password',
            forgotPassword: 'Forgot Password?',
            rememberme: 'Remember me',
            donthaveaccount: 'Don’t have account?',
            signup: 'SIGN UP',
            or: 'OR',
            signIn: 'SIGN IN',
            pleaseRegisterHere: 'Please Register Here!',
            fullname: 'Full Name',
            confirmpassword: 'Confirm password',
            role: 'Role',
            alreadyhaveanaccount: 'Already have an account ',
            iagreeto: 'I agree to',
            TermsConditions: 'Terms & Conditions',
            and1: '&',
            privacyPolicy: 'Privacy Policy',
            otp: 'OTP',
            enter6digitcode: 'Enter 6 digit code sent to your email address to verify your identity',
            sendagain: 'Send again',
            verify: 'VERIFY',
            success: 'Success',
            registerissucessfullyhaveenjoy: 'Register is sucessfully have enjoy!',
            resetyourpassword: 'Reset your password',
            enteryouremail: 'Enter your email address to reset your Password',
            rememberyourpassword: 'Remember your password?',
            sendOtp: 'SEND OTP',
            changePassword: 'Change password',
            enteryournewpassword: 'Enter your new password to access to your account',
            save: 'SAVE',
            home: 'Home',
            booking: 'Booking',
            map: 'Map',
            notification: 'Notification',
            profile: 'Profile',
            Favorites: 'Favorites',
            paymentMethod: 'Payment Method',
            referralDiscounts: 'Referral Discounts',
            preferences: 'Preferences',
            fAQ: 'FAQ',
            settings: 'Settings',
            editProfile: 'Edit Profile',
            phoneNo: 'Phone No',
            address: 'Address',
            gender: 'Gender',
            male: 'Male',
            female: 'Female',
            SAVE: 'SAVE',
            notificationReceivedw: 'Notification received',
            new: 'New',
            allFavorites: 'All Favorites',
            discountinFavorites: 'Discount in Favorites',
            creditCards: 'Credit Cards',
            addanewcard: 'Add a new card',
            cardNumber: 'Card Number',
            cvvNumber: 'CVV Number',
            expiryDate: 'Expiry Date',
            creditDebitCard: 'Credit/Debit Card',
            getfreecredit: 'Get Free Credit',
            sharethebestkepthome: "Share the best-kept home care secret! Share the link to give your friend ILT 40 off their booking! Once they use it to book, you will automatically receive ILT 40 credit added to your account! Now that's what we call a win-win-win!",
            sharefreecredit: 'Share free credit',
            office: 'Office',
            company: 'Company',
            hospital: 'Hospital',
            flexibletime: 'Flexible time ',
            recurring: 'Recurring',
            service: 'Service',
            request: 'Request',
            cleaning: 'Cleaning',
            preferences: 'Preferences',
            search: 'Search',
            howdoibookacleaning: 'How do I book a cleaning service?',
            howdoipayforthe: 'How do I pay for the cleaning services?',
            howdoicontact: 'How do I contact customer support?',
            feedback: 'Feedback',
            supportandhelp: 'Support & Help Center',
            deletemyaccount: 'Delete my account',
            tellusaboutyour: 'Tell us about your experience',
            yourfeedback: 'Your feedback',
            send: 'SEND',
            support: 'Support',
            deleteacount: 'Delete Account',

            areyousureyouwant: 'Are you sure you want to delete your account?',
            warning: 'Warning:',
            deleting: 'Deleting your account will permanently remove all of your:',
            bookingHistory: 'Booking history',
            savedpayment: 'Saved payment methods',
            personalPrefrences: 'Personal preferences',
            todeleteyouraccount: 'To Delete your Account Confirm your Password',
            password: 'Password',
            bytappingconfirm: 'By tapping confirm, you agree to the',
            of: 'of',
            clein: 'CLE IN',
            enterpassword: 'Enter password',
            delete: 'DELETE',
            specialservices: 'Special Services',
            cleaningathome: 'Cleaning at Home',
            cleaningatcompany: 'Cleaning at Company',
            cleaningathospital: 'Cleaning at Hospital',
            cleaningatoffice: 'Cleaning at Offices',
            cleaningatfactory: 'Cleaning at Factory',
            serviceprovider: 'Service Provider',
            book: 'BOOK',
            title: 'Title',
            description: 'Description',
            price: 'Price',
            location: 'Location',
            reviews: 'Reviews',
            seeAll: 'See All',
            news: '',
        }
    },
    {
        locale: 'cz',
        translation: {

        }
    },
    {
        locale: 'ur',
        translation: {

        }
    },

];

export const appLanguages = [
    {
        id: '0',
        name: 'English',
        code: 'en'
    },
    {
        id: '1',
        name: 'Czech',
        code: 'cz'
    },
    {
        id: '2',
        name: 'Urdu',
        code: 'ur'
    },
];
